/**
 * Created by a on 10/29/2015.
 */

module.exports=function(app){

    var async = require('async');
    var extend = require('extend');

    var item_db = app.locals.dbs.items.handler;


    var store_item = function(doc, next,res){

        //store the doc in the queries db
        //the primary key is the id autogenerated

        item_db.insert(doc,null,function(err,body){
            if (!err)
                console.log('stored correctly with information as ' + body);
            else
                console.log(err);
            next(res);
        });
    };

    var retrieve_items = function(res){

        var titles=[];

        item_db.list({include_docs:true},function(err,body){
            if (!err){

                //should contain _id with the title
                body.rows.forEach(function(doc){
                    var element = {};
                    element.title = doc.doc.title;
                    element.id = doc.key;
                    element.primary_url = doc.doc.primary_url;
                    titles.push(element);
                });
            }

            if (titles.length > 0 )
            {
                res.json({titles:titles});

            }else
                res.status(500).send({status:'error'});

        });
    }

    //retrieve all of the titles from the doc
    app.get('/items/titles',function(req,res){

       //returns the _id and titles
       retrieve_items(res);
    });

    //retrieve the doc with the _id
    //body
    //{ _id: doc_id}
    app.get('/items/found', function(req,res){

        var doc_id = req.query.id;

        console.log("received id " + doc_id);

        item_db.get(doc_id, {revs_info:true}, function(err,body){
            if (!err){
                //return the found list of the doc
                console.log("retieved body " + JSON.stringify(body));

                res.json({title: body.title,
                    description:body.description,
                    found:body.found});
            }else {
                res.status(404).send({status: err});
            }

        } );

    });

    app.post('/items/submit', function(req, res){

        item_doc = JSON.parse(Object.keys(req.body)[0]);

        console.log(JSON.stringify(item_doc));

        //store the query in the queries db
        // for one query, currently, there is one document including
        // original query,
        // the recommendations retrieved by concept insights from concept insights
        // the concepts of the query,
        // and the relationship extracted from the query

        store_item(item_doc, retrieve_items, res);

    });
}